import type { PatientDemographics } from '../../../types/index';

export const DEFAULT_DEMOGRAPHICS: PatientDemographics = {
  id: '',
  name: '',
  mrn: '',
  dob: '',
  gender: 'male',
  phone: '',
  address: '',
  height: 0,
  weight: 0,
  bmi: 0,
  surgeryDate: '',
  symptomDate: '',
  isAcute: false,
  implantType: 'TKA',
  fixationType: 'cemented',
  implantNature: 'Primary',
  comorbidities: {
    diabetes: false,
    smoking: false,
    immunosuppression: false,
    priorInfection: false,
    malnutrition: false,
    liverDisease: false,
  },
  medicalHistory: '',
  pastMedicalHistory: '',
  relatedCharacteristics: {
    allergy: { checked: false, note: '' },
    drugs: { checked: false, note: '' },
    alcohol: { checked: false, note: '' },
    smoking: { checked: false, note: '' },
    other: { checked: false, note: '' },
  },
  surgicalHistory: [{ id: '1', surgeryDate: '', procedure: '', notes: '' }],
};
